version: '3'

services:
  producer:
    build: ./producer
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  consumer_one:
    build: ./consumer_one
    depends_on:
      - rabbitmq

  consumer_two:
    build: ./consumer_two
    depends_on:
      - rabbitmq

  consumer_three:
    build: ./consumer_three
    depends_on:
      - rabbitmq

  consumer_four:
    build: ./consumer_four
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
